apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm: # gcpsm provider
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: secret-puller
            key: creds
      projectID: devops-386509
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: configs
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: app-secrets  # name of the k8s Secret to be created
    # Enum with values: 'Owner', 'Merge', or 'None'
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: test1-secrets
        version: latest
